#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /tmp

echo "Welcome to Linux Lab minimal rootfs"
echo "Kernel: $(uname -r) on $(uname -m)"
